# KNN Imputer

The KNN Imputer is a method for filling in missing values in a dataset using the K-Nearest Neighbors (KNN) algorithm. It works by finding the k most similar instances (rows) to the one with missing data and imputing the missing values based on the values from those neighbors.

## How it Works?

1. Find k nearest neighbors (based on other features without missing values).
2. Calculate the mean (or weighted average) of the same feature in those neighbors.
3. Impute the missing value with that result.

## When To Use?

1. Data is missing at random.
2. Features are numerical or standardized.
3. Dataset size is manageable (KNN can be slow for large datasets).

In [2]:
# working

dist(x,y) = sqrt(weight * sq. distance from present coordinates)

weight = Total # of coordinates / # of present coordinates

For example, the distance between [3, na, na, 6] and [1, na, 4, 5] is:

root(4/2(3-1)**2 + (6-5)**2)

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('train.csv')

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
new = df[['Age','Pclass','Fare','Survived']]

In [8]:
new.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [9]:
x = new.drop('Survived',axis=1)
y = new['Survived']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [1]:
from sklearn.impute import KNNImputer

In [28]:
knn = KNNImputer()

x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [29]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

      Age  Pclass      Fare
0    45.5     1.0   28.5000
1    23.0     2.0   13.0000
2    32.0     3.0    7.9250
3    26.0     3.0    7.8542
4     6.0     3.0   31.2750
..    ...     ...       ...
707  21.0     3.0    7.6500
708  44.1     1.0   31.0000
709  41.0     3.0   14.1083
710  14.0     1.0  120.0000
711  21.0     1.0   77.2875

[712 rows x 3 columns]

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)
y_pred = lr.predict(x_test_trf)

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy_score(y_test,y_pred)

0.7374301675977654

In [34]:
# uniform and distance

Uniform -- by default same 
distance -- we calculate the value by multiplying with reciprocal of the distance

# Categorical Columns

1. most_frequent value(Mode)
2. Just write Missing

## most_frequent value

In [35]:
from sklearn.impute import SimpleImputer

In [36]:
SimpleImputer(strategy='most_frequent')

SimpleImputer(strategy='most_frequent')

In [ ]:
# df.fillna('missing',inplace=True)