# Column Transformer

The ColumnTransformer is a powerful tool in sklearn.compose used to apply different preprocessing techniques to different columns of a dataset — all in a single step.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
x = df.drop('has_covid',axis=1)

In [6]:
y = df['has_covid']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.compose import ColumnTransformer

In [10]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [16]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
    
],remainder='passthrough')

In [17]:
transformer.fit_transform(x_train)

array([[101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [100.,   0.,   1.,   0.,   0.,   0.,  11.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [ 98.,   0.,   1.,   0.,   0.,   0.,  73.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.]])

In [18]:
transformer.transform(x_test)

array([[104.,   0.,   0.,   0.,   1.,   0.,  17.],
       [ 98.,   0.,   1.,   1.,   0.,   0.,  83.],
       [101.,   1.,   0.,   1.,   0.,   0.,  68.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  72.],
       [102.,   1.,   1.,   1.,   0.,   0.,  20.],
       [103.,   0.,   0.,   0.,   1.,   0.,  50.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  71.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  14.],
       [101.,   0.,   0.,   1.,   0.,   0.,  75.],
       [103.,   0.,   1.,   0.,   1.,   0.,  60.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [101.,   0.,   1.,   1.,   0.,   0.,  15.],
       [ 98.,   1.,   1.,   0.,   1.,   0.,  34.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  26.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [101.,   0.,   0.,   0.,   0.,   1.,  65.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [101.,   0.,   0.,   0.,   1.,   0.,   8.],
       [ 99.,   1.,   0.,   0.,   1.,   0.,  25.],
       [103.,   0.,   1.,   0.,   1.,   0.,  83.]])

In [20]:
transformer.named_transformers_['tnf3'].get_feature_names_out()

array(['gender_Male', 'city_Delhi', 'city_Kolkata', 'city_Mumbai'],
      dtype=object)

In [158]:
ohe = transformer.named_transformers_['tnf3']
ohe.get_feature_names_out(['gender', 'city'])

array(['gender_Male', 'city_Delhi', 'city_Kolkata', 'city_Mumbai'],
      dtype=object)

In [159]:
sm = transformer.named_transformers_['tnf1']
sm.get_feature_names_out(['fever'])

array(['fever'], dtype=object)

In [160]:
sm = transformer.named_transformers_['tnf2']
sm.get_feature_names_out(['cough'])

array(['cough'], dtype=object)

# Pipelines

Pipelines chains together mutliple steps so that the ouptput of each step is used as input to the next step.
Pipelines makes it easy to apply the preprocessing to train and test.

In [21]:
new = pd.read_csv('train.csv')

In [22]:
new.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
new.drop(columns=['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [24]:
new.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [25]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(new.drop('Survived',axis=1),
                                                 new[['Survived']],test_size=0.2,random_state=42)

In [26]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

In [31]:

# Categorical pipeline
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore'))
])

# Numerical pipeline
num_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', MinMaxScaler())
])

# Column transformer
preprocessor = ColumnTransformer([
    ('cat', cat_pipe, ['Sex', 'Embarked']),
    ('num', num_pipe, ['Age', 'Fare'])
], remainder='passthrough')

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', DecisionTreeClassifier())
])

In [35]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Sex', 'Embarked']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Age', 'Fare'])])),
                ('model', DecisionTreeClassifier())])

In [36]:
y_pred = pipe.predict(x_test)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_test,y_pred)

0.7988826815642458